# Automatically generated by configure
prefix=/mingw
libdir=${prefix}/lib
incdir=${prefix}/include
AR=ar
CC=gcc
RANLIB=ranlib
STRIP=strip
BUILD_SHARED=no
BUILD_STATIC=yes
BUILD_MSVC=
LIBCMD=@echo ignoring lib
WINE=
